wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.6
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714017724.0
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.11.9
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
